[package]
name = "telescope"
version = "0.2.0"
authors = [
    "Antonia \"Nia\" Calia-Bogan <acaliabogan@acaliabogan.dev>"
]
description = "The RCOS webapp"

edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
# command line argument parser
structopt = "~0.3"
# environment variable reading through dotenv (.env files)
dotenv = "~0.15"
# config file reading
toml = "~0.5"
# actix actor framework -- system for running server and other tasks.
actix = "~0.10"
# actix web server (use exact version)
actix-web = {version = "~3.3", features = ["openssl"]}
# static file serving
actix-files = "~0.5"
# identity service -- cookie authentication
actix-identity = "~0.3"
# ratelimiting (not compatible with actix 3)
#actix-ratelimit = "~0.2"
# redirect all traffic over https.
actix-web-middleware-redirect-scheme = "~3.0"
# html templating.
handlebars = {version = "~3.5", features = ["dir_source"]}
# tls/ssl certification.
openssl = {version = "~0.10", features = ["vendored"]}
# exit code standardization
exitcode = "~1.0"
# logging
log = "~0.4"
env_logger = "~0.8"
# (de)serialization
serde = {version = "~1.0", features = ["derive"]}
serde_json = "~1.0"
# generating QR codes (will be useful later for attendance QR codes perhaps)
qrcodegen = "~1.6"
# cryptographically sound random number generation
rand = "~0.8"
# lazily evaluated statics.
lazy_static = "~1.4"
# utilities for dealing with async futures
futures = "~0.3"
# Pasword hashing and verification
rust-argon2 = "~0.8"
# Regular expressions
regex = "~1.4"
# Markdown - HTML rendering
pulldown-cmark = "~0.8"
# Sending emails.
lettre = {version = "~0.9", features = ["serde-impls"]}
lettre_email = "~0.9"
# MD5 hashing to use to talk to Gravatar.
md5 = "~0.7"
# URL Parsing
url = "~2.2"
# Date and time utilities
chrono = {version = "~0.4", features = ["serde", "std", "clock"]}
time = {version = "~0.2", features = ["serde", "std"]}
# ORM and query building (to interact with Postgres Database)
diesel = {version = "~1.4", features = ["uuidv07", "r2d2", "postgres", "chrono"]}
# Universally unique identifier generation
uuid = {version = "~0.8", features = ["serde", "v4"]}

# Async functions in traits
# Add this in when you have time (see src/templates/static_pages)
# async-trait = "~0.1"
