[package]
name = "telescope"
version = "0.1.0"
authors = ["Antonia Calia-Bogan <acaliabogan@acaliabogan.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
