[package]
name = "telescope"
version = "0.1.0"
authors = [
    "Antonia \"Nia\" Calia-Bogan <acaliabogan@acaliabogan.dev>"
]
description = "The RCOS webapp"

edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
# command line argument parser
structopt = "0.3"
# environment variable reading through dotenv (.env files)
dotenv = "0.15.0"
# actix web server
actix-web = {version = "2.0.0", features = ["openssl"]}
# actix runtime
actix-rt = "1.0.0"
# static file serving
actix-files = "~0.2"
## session cookies
#actix-session = "0.3.0"
# identity service -- cookie authentication
actix-identity = "0.2"
# ratelimiting
actix-ratelimit = "0.2.1"
# html templating.
handlebars = {version = "3.1.0", features = ["dir_source"]}
# tls/ssl certification.
openssl = {version = "0.10", features = ["vendored"]}
# exit code standardization
exitcode = "1"
# logging
log = "0.4.8"
env_logger = "0.7"
# (de)serialization
serde = {version = "1", features = ["derive"]}
serde_json = "1"
# generating QR codes (will be useful later for attendance QR codes perhaps)
qrcodegen = "1.6.0"
# cryptographically sound random number generation
rand = "0.7"
# lazily evaluated statics.
lazy_static = "1.4.0"
# utilities for dealing with async futures
futures = "0.3"
# Pasword hashing and verification
rust-argon2 = "0.8"
# Universally unique identifier generation
uuid = {version = "0.7", features = ["serde", "v4"]}
# ORM and query building (to interact with Postgres Database)
diesel = {version = "1.4.5", features = ["postgres", "r2d2", "uuidv07", "chrono", "serde_json"]}
# GraphQL queries and API system.
juniper = "0.14.2"
# Date/Time utilities
chrono = {version = "0.4", features = ["serde"]}
# Regular expressions
regex = "1"
# Markdown - HTML rendering
pulldown-cmark = "0.8"
# Sending emails.
lettre = {version = "0.9", features = ["serde-impls"]}