# The Telescope Config format is a serialized version
# of the structures in src/env.rs.
#
# For anyone using or developing telescope, this configuration template should
# be copied to config.toml and then modified to your needs.
#
# This file only contains 3 profiles (development, prodcution)
# but users may specify more arbirarilty using the profile objects.
# Profiles may override any/all of the global settings.
#
# Each required config option must be specified somewhere, either top-level
# or in some level of the active profile (which is specified using commandline arguments).
#
# Any option specified at top level and in a profile (or subprofile) is resolved
# as the specification with the most depth. when `telescope=trace` is active in
# the log level options then the options active at runtime are logged on server
# start up.
#

# [REQUIRED]
# specify the log level of the telescope server instance
# see https://docs.rs/env_logger/0.8.1/env_logger/ for syntax and options.
log_level = "info"

# [REQUIRED]
# specify the database url of the postgres database created using diesel
# earlier in setup (as specified in the README)
database_url = "postgres://username:password@localhost/telescope"

# [REQUIRED]
# Specify the location to bind the running server.
bind_to = "localhost:8443"

# [REQUIRED]
# The TLS/SSL configurations. These are specified as the paths of the
# TLS/SSL credentials generated earlier in the setup (see the readme), or
# in production environments isssued by a certificate authority.
[tls_config]
# [REQUIRED]
# The TLS/SSL certification file.
cert_file = "tls-ssl/certificate.pem"
# [REQUIRED]
# The TLS/SSL private key chain file.
private_key_file = "tls-ssl/private-key.pem"

# [OPTIONAL]
# These options (when specified) will be used to add a sysadmin account
# the Telescope database on startup. This only has to be done once, unless the
# database gets erased.
[sysadmin_config]
# [REQUIRED]
# The email to be used to login to the sysadmin account.
email = "admin@test.rcos.io"
# [REQUIRED]
# The password to be used to login to the sysadmin account.
# This has to be within the password requirements (so "password" won't work).
password = "password"
# [REQUIRED]
# This must be set to true for the sysadmin account to be created on startup.
# This is mostly for convenience. It can be set to false once a sysadmin account
# has been created.
create = false

# [REQUIRED]
# These settings specify what to do with emails generated by the server.
[email_config]
# [OPTIONAL]
# The name used to sign emails sent by the server.
name = "RCOS Telescope"
# [REQUIRED]
# The email address that emails are sent from.
address = "telescope@rcos.io"
# [REQUIRED]
# Should the emails generated by the server be printed to the terminal in
# a log message? Very useful for development, but probably undesireable for
# production environments.
stub = true
# [OPTIONAL]
# specify a path to save generated emails in text files.
file = "/tmp"
# [OPTIONAL]
# Send the emails to users from an email account using SMTP.
[email_config.smtp]
# [REQUIRED]
# The SMTP server.
host = "smtp.rcos.io"
# [REQUIRED]
# The port of the SMTP server to connect to as a client.
port = 000
# [REQUIRED]
# The username to login to the email. This is usually the part of the
# email address before the @ symbol.
username = "telescope"
# [REQUIRED]
# The password to use to sign into the SMTP server.
password = "password"


# Development Profile
# These options will override the global ones when telescope is run using
# `telescope -p dev`
[profile.dev]
log_level = "info,telescope=trace"

# Sysadmin development subprofile.
# This uses all the options specified in the dev profile and
# also overrides the sysadmin config.
# Use `telescope -p dev.create_sysadmin`
[profile.dev.profile.create_sysadmin.sysadmin_config]
email = "test@mydomain.test"
password = "BetterPassword"
create = true

# Production profile.
# Use `telescope -p production`
[profile.production]
bind_to = "0.0.0.0:443"
