version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    network_mode: host
  telescope:
    restart: "no"
    depends_on:
      - db
    build: .
    environment:
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}"
    ports:
    - "80:8080"
    - "443:8443"
