version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    expose:
      - "5432"
  telescope:
    restart: "no"
    depends_on:
      - db
    build: .
    ports:
    - "80:8080"
    - "443:8443"
