version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
    - "5432:5432"
    - "5432:5432/udp"
    healthcheck:
      test: ["CMD", "curl", "postgres://db"]
      interval: 30s
      timeout: 10s
      retries: 5
      
  telescope:
    restart: "no"
    depends_on:
      db:
        condition: service_healthy
    build: .
    ports:
    - "80:8080"
    - "443:8443"
