version: "3.2"

services:
  db:
    image: postgres
    restart: on-failure
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - "5432:5432"

  telescope:
    restart: on-failure
    depends_on:
      - db
    build: .
    ports:
      - "80:8080"
      - "443:8443"
